# Instructions

### At this point, we have created a model to predict who will make a donation and who won't. But, what about the ammount of money that each person will give? In this lab, subset those that made a donation and use that subset to create a model to predict how much money will they give.

### Evaluate the result of your model and estimate how much better the result are for the bussiness in comparison with the naive scenario we discuss on Monday.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
categorical = pd.read_csv('categorical.csv')
numerical = pd.read_csv('numerical.csv')
target = pd.read_csv('target.csv')

data = pd.concat([categorical,numerical,target],axis=1)

In [3]:
data.head()

,STATE,CLUSTER,HOMEOWNR,GENDER,DATASRCE,RFA_2R,RFA_2A,GEOCODE2,DOMAIN_A,DOMAIN_B,...,MAXRAMNT,LASTGIFT,TIMELAG,AVGGIFT,CONTROLN,HPHONE_D,RFA_2F,CLUSTER2,TARGET_B,TARGET_D
0,IL,36,H,F,3,L,E,C,T,2,...,12.0,10.0,4,7.741935,95515,0,4,39,0,0.0
1,CA,14,H,M,3,L,G,A,S,1,...,25.0,25.0,18,15.666667,148535,0,2,1,0,0.0
2,NC,43,U,M,3,L,E,C,R,2,...,16.0,5.0,12,7.481481,15078,1,4,60,0,0.0
3,CA,44,U,F,3,L,E,C,R,2,...,11.0,10.0,9,6.812500,172556,1,4,41,0,0.0
4,FL,16,H,F,3,L,F,A,S,2,...,15.0,15.0,14,6.864865,7112,1,2,26,0,0.0

In [4]:
target_d = data[data['TARGET_B']==1]

In [5]:
target_d.shape

(4843, 339)

In [6]:
target_d.head()

,STATE,CLUSTER,HOMEOWNR,GENDER,DATASRCE,RFA_2R,RFA_2A,GEOCODE2,DOMAIN_A,DOMAIN_B,...,MAXRAMNT,LASTGIFT,TIMELAG,AVGGIFT,CONTROLN,HPHONE_D,RFA_2F,CLUSTER2,TARGET_B,TARGET_D
20,other,12,H,F,3,L,D,A,S,1,...,7.0,5.0,12,4.066667,82943,1,3,3,1,4.0
30,TX,35,H,M,3,L,D,A,T,1,...,10.0,7.0,9,6.181818,190313,1,3,14,1,7.0
45,other,24,H,F,3,L,D,C,C,1,...,6.0,5.0,3,4.857143,76585,1,3,11,1,5.0
78,CA,13,H,F,2,L,F,A,S,1,...,17.0,10.0,21,11.000000,156378,0,2,2,1,13.0
93,GA,18,H,M,3,L,E,A,S,2,...,12.0,12.0,6,9.400000,25641,1,3,22,1,10.0

In [7]:

X = target_d.drop(['TARGET_B','TARGET_D'],axis=1)
y = target_d['TARGET_D']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
#cat/num X-train
X_train_num = X_train.select_dtypes(include = np.number)
X_train_cat = X_train.select_dtypes(object)

#cat/num X-test
X_test_num = X_test.select_dtypes(include = np.number)
X_test_cat = X_test.select_dtypes(object)


from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
#Scale X-train
transformer = MinMaxScaler().fit(X_train_num)
X_scaled_train = pd.DataFrame(transformer.transform(X_train_num),columns=X_train_num.columns)

#Scale X-test
X_scaled_test = pd.DataFrame(transformer.transform(X_test_num),columns=X_test_num.columns)
X_scaled_test

,CLUSTER,DATASRCE,DOMAIN_B,ODATEW_YR,ODATEW_MM,DOB_YR,DOB_MM,MINRDATE_YR,MINRDATE_MM,MAXRDATE_YR,...,CARDGIFT,MINRAMNT,MAXRAMNT,LASTGIFT,TIMELAG,AVGGIFT,CONTROLN,HPHONE_D,RFA_2F,CLUSTER2
0,0.000000,0.5,0.000000,0.909091,0.0,0.351648,0.000000,0.909091,0.000000,0.909091,...,0.034483,0.044444,0.015075,0.044444,0.204545,0.039619,0.908238,0.0,0.000000,0.426230
1,0.865385,0.5,0.333333,0.000000,0.0,0.000000,0.090909,0.090909,0.454545,0.818182,...,0.379310,0.006667,0.010050,0.033333,0.113636,0.010920,0.709809,0.0,0.000000,0.885246
2,0.846154,1.0,0.333333,0.818182,0.0,0.527473,0.000000,0.727273,1.000000,0.818182,...,0.000000,0.011111,0.015075,0.044444,0.272727,0.022869,0.549203,1.0,0.000000,0.950820
3,0.538462,1.0,0.333333,0.000000,0.0,0.164835,0.090909,0.181818,1.000000,0.545455,...,0.448276,0.004444,0.001005,0.011111,0.590909,0.004877,0.231312,0.0,0.666667,0.196721
4,0.846154,1.0,0.333333,0.818182,0.0,0.461538,0.000000,0.818182,0.909091,0.818182,...,0.137931,0.006667,0.001005,0.008889,0.113636,0.005001,0.333525,0.0,1.000000,0.704918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,0.673077,1.0,0.333333,0.636364,0.0,0.318681,1.000000,0.636364,0.090909,0.727273,...,0.068966,0.011111,0.010050,0.033333,0.500000,0.021007,0.330735,0.0,0.000000,0.852459
965,0.653846,1.0,0.000000,0.545455,0.0,0.000000,0.090909,0.545455,0.818182,0.818182,...,0.241379,0.011111,0.010050,0.022222,0.068182,0.021938,0.683392,0.0,0.333333,0.229508
966,1.000000,1.0,0.666667,0.545455,0.0,0.626374,0.000000,0.545455,0.363636,0.909091,...,0.137931,0.011111,0.020101,0.055556,0.250000,0.030686,0.388096,0.0,0.333333,0.950820
967,0.250000,1.0,0.000000,0.363636,0.0,0.263736,0.000000,0.363636,0.090909,0.818182,...,0.103448,0.011111,0.010050,0.028889,0.250000,0.017843,0.822848,1.0,0.333333,0.065574
968,0.346154,1.0,0.333333,0.818182,0.0,0.000000,0.090909,0.818182,0.090909,0.818182,...,0.034483,0.022222,0.011055,0.035556,0.159091,0.023985,0.806692,0.0,0.000000,0.409836

In [10]:
from sklearn.preprocessing import OneHotEncoder
#Create encoder
encoder = OneHotEncoder(drop='first').fit(X_train_cat)

#encode train
encoded_train = encoder.transform(X_train_cat).toarray()
encoded_train = pd.DataFrame(encoded_train)

#encode test
encoded_test = encoder.transform(X_test_cat).toarray()
encoded_test = pd.DataFrame(encoded_test)

In [11]:
train_scaled = pd.concat([encoded_train,X_scaled_train],axis=1)
test_scaled = pd.concat([encoded_test,X_scaled_test],axis=1)

In [12]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')

In [13]:
DT = DecisionTreeRegressor()
LR = LinearRegression()
xgb = XGBRegressor()
RF = RandomForestRegressor()

model_pipeline = [DT, LR, xgb, RF]
model_names = ['Regression Tree', 'Linear Regression','XGBoost','Random Forest']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, train_scaled, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': -0.04151769465804404, 'Linear Regression': 0.4117895634825743, 'XGBoost': 0.4353661933023787, 'Random Forest': 0.5167291973557602}

In [14]:
val_scores = {}
i=0
for model in model_pipeline:
    model.fit(train_scaled, y_train)
    val_scores[model_names[i]] = model.score(test_scaled,y_test)
    i = i+1
print(val_scores)

{'Regression Tree': -0.012314212792175372, 'Linear Regression': 0.28955295013363247, 'XGBoost': 0.26087543353167375, 'Random Forest': 0.4176905547153442}

In [15]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from math import sqrt

LR =RandomForestRegressor().fit(train_scaled, y_train)
pred = LR.predict(test_scaled)

In [16]:
r2 = r2_score(y_test,pred)
mse = mean_squared_error(y_test,pred)
mae = mean_absolute_error(y_test,pred)
rmse = sqrt(mse)

In [18]:
print('R2 Score:', r2)
print('Mean Squared Error:', mse)
print('Mean absolute Error:', mae)
print('Root Mean Squared Error:',rmse)

R2 Score: 0.3921615892512076
Mean Squared Error: 115.83252835357068
Mean absolute Error: 4.837020123839009
Root Mean Squared Error: 10.762552130120936

In [19]:
# how much will the donators give?
round(np.mean(pred),2)

16.45